### ISSUE TITLE
Imagem de fundo do #landing_hero está muito grande

### ISSUE THREAD

**Issue by PedroCabs** [matheusfdosan/MelhorCidade_FrontEnd#2]
Poderia ser do seguinte tamanho:

```css
@media (min-width: 1115px) {
  height: 78vh;
}
```
