### ISSUE TITLE
Tela de Cadastro está errada

### ISSUE THREAD

**Issue by PedroCabs** [matheusfdosan/MelhorCidade_FrontEnd#3]
Ela não está ocupando 100% da altura:

```css
#signup_container {
  height: 100vh;
}
```
